version: '3.8'  # 指定 Docker Compose 版本
services:
  web:
    build: .  # 使用当前目录的 Dockerfile 构建镜像
    ports:
      - "30001:30001"  # 映射端口（根据你的项目调整）
    depends_on:
      - db  # 依赖 MySQL 服务
    environment:
      - MYSQL_HOST=db  # MySQL 主机名（服务名）
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=server_data
    networks:
      - app-network

  db:
    image: mysql:8.0  # 使用官方 MySQL 镜像
    command: --default-authentication-plugin=mysql_native_password  # 兼容旧版认证
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: server_data
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/mysql  # 持久化数据
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化脚本
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: